#include "utils/utils.h"

typedef enum OBJECT_TYPE
{
	OBJECT_TYPE_NULL,
	OBJECT_TYPE_UNKNOWN,
	OBJECT_TYPE_TYPE,
	OBJECT_TYPE_DIRECTORY,
	OBJECT_TYPE_SYMBOLICLINK,
	OBJECT_TYPE_TOKEN,
	OBJECT_TYPE_JOB,
	OBJECT_TYPE_PROCESS,
	OBJECT_TYPE_THREAD,
	OBJECT_TYPE_PARTITION,
	OBJECT_TYPE_USERAPCRESERVE,
	OBJECT_TYPE_IOCOMPLETIONRESERVE,
	OBJECT_TYPE_ACTIVITYREFERENCE,
	OBJECT_TYPE_PSSILOCONTEXTPAGED,
	OBJECT_TYPE_PSSILOCONTEXTNONPAGED,
	OBJECT_TYPE_DEBUGOBJECT,
	OBJECT_TYPE_EVENT,
	OBJECT_TYPE_MUTANT,
	OBJECT_TYPE_CALLBACK,
	OBJECT_TYPE_SEMAPHORE,
	OBJECT_TYPE_TIMER,
	OBJECT_TYPE_IRTIMER,
	OBJECT_TYPE_PROFILE,
	OBJECT_TYPE_KEYEDEVENT,
	OBJECT_TYPE_WINDOWSTATION,
	OBJECT_TYPE_DESKTOP,
	OBJECT_TYPE_COMPOSITION,
	OBJECT_TYPE_RAWINPUTMANAGER,
	OBJECT_TYPE_COREMESSAGING,
	OBJECT_TYPE_ACTIVATIONOBJECT,
	OBJECT_TYPE_TPWORKERFACTORY,
	OBJECT_TYPE_ADAPTER,
	OBJECT_TYPE_CONTROLLER,
	OBJECT_TYPE_DEVICE,
	OBJECT_TYPE_DRIVER,
	OBJECT_TYPE_IOCOMPLETION,
	OBJECT_TYPE_WAITCOMPLETIONPACKET,
	OBJECT_TYPE_FILE,
	OBJECT_TYPE_TMTM,
	OBJECT_TYPE_TMTX,
	OBJECT_TYPE_TMRM,
	OBJECT_TYPE_TMEN,
	OBJECT_TYPE_SECTION,
	OBJECT_TYPE_SESSION,
	OBJECT_TYPE_KEY,
	OBJECT_TYPE_REGISTRYTRANSACTION,
	OBJECT_TYPE_ALPC_PORT,
	OBJECT_TYPE_ENERGYTRACKER,
	OBJECT_TYPE_POWERREQUEST,
	OBJECT_TYPE_WMIGUID,
	OBJECT_TYPE_ETWREGISTRATION,
	OBJECT_TYPE_ETWSESSIONDEMUXENTRY,
	OBJECT_TYPE_ETWCONSUMER,
	OBJECT_TYPE_COVERAGESAMPLER,
	OBJECT_TYPE_DMAADAPTER,
	OBJECT_TYPE_PCWOBJECT,
	OBJECT_TYPE_FILTERCONNECTIONPORT,
	OBJECT_TYPE_FILTERCOMMUNICATIONPORT,
	OBJECT_TYPE_NDISCMSTATE,
	OBJECT_TYPE_DXGKSHAREDRESOURCE,
	OBJECT_TYPE_DXGKSHAREDKEYEDMUTEXOBJECT,
	OBJECT_TYPE_DXGKSHAREDSYNCOBJECT,
	OBJECT_TYPE_DXGKSHAREDSWAPCHAINOBJECT,
	OBJECT_TYPE_DXGKDISPLAYMANAGEROBJECT,
	OBJECT_TYPE_DXGKCURRENTDXGTHREADOBJECT,
	OBJECT_TYPE_DXGKSHAREDPROTECTEDSESSIONOBJEC,
	OBJECT_TYPE_DXGKSHAREDBUNDLEOBJECT,
	OBJECT_TYPE_DXGKCOMPOSITIONOBJECT,
	OBJECT_TYPE_VREGCONFIGURATIONCONTEXT
}OBJECT_TYPE;

BOOL GetObHeaderCookie(BYTE* ObHeaderCookie)
{
	BYTE* eprocess = 0;
	if (FindProcessByName("System", (PEPROCESS*)&eprocess))
	{
		BYTE num1 = *(eprocess - 0x18);
		BYTE num2 = (BYTE)(((ULONG64)((BYTE*)eprocess - 0x30)) >> 8);

		*ObHeaderCookie = num1 ^ num2 ^ OBJECT_TYPE_PROCESS;

		return TRUE;
	}
	return FALSE;
}

BOOL SetObjectType(BYTE* eprocess, BYTE ObjectType)
{
	BYTE ObHeaderCookie;
	GetObHeaderCookie(&ObHeaderCookie);

	BYTE* objtype = (BYTE*)eprocess - 0x18;

	BYTE num1 = (BYTE)(((ULONG64)eprocess - 0x30) >> 8);
	*objtype = ObjectType ^ ObHeaderCookie ^ num1;

	return TRUE;
}

NTSTATUS DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath)
{
	UNREFERENCED_PARAMETER(DriverObject);
	UNREFERENCED_PARAMETER(RegistryPath);

	PEPROCESS eprocess;
	if (FindProcessByName("notepad.exe", &eprocess))
	{
		SetObjectType((BYTE*)eprocess, OBJECT_TYPE_JOB);
	}

	return STATUS_UNSUCCESSFUL;
}